### PR TITLE
PyTorch 1.11 Docker Image

### LINKED ISSUE #847: Segmentation Fault in CPU Test
** Environment **

- OS: [Ubuntu 20.04]
- Hardware (GPU, or instance type): [GEFORCE 3080]

Not CUDA related

** To reproduce

1. make test

## Expected behavior

Tests should pass

## Additional context

Hi there! I am preparing my application for the research engineer role at Mosaic, and I thought I would start by contributing to this awesome repo! After I install dependencies and run the CPU test, I receive the following error. This error is not CUDA related because GPU and distributed GPU tests both pass, but not CPU or distributed CPU tests. The error seems to be pointing to the line `trainer.fit()`, but I have also made sure that the trainer runs properly when I run normal training. That's why I am confused as to why this error would happen.

```
▶ make test                                    
python   -m pytest    --duration all  
=================================================================== test session starts ====================================================================
platform linux -- Python 3.8.12, pytest-7.1.0, pluggy-1.0.0
rootdir: /workspace/composer, configfile: pyproject.toml
plugins: timeout-2.1.0
timeout: 2.0s
timeout method: signal
timeout func_only: False
collected 1659 items / 223 deselected / 1436 selected                                                                                                      

tests/test_dataset_registry.py .x...xxxxsssssss                                                                                                      [  1%]
tests/test_device.py ......                                                                                                                          [  1%]
tests/test_engine.py ...................................................................................................                             [  8%]
tests/test_events.py .......................                                                                                                         [ 10%]
tests/test_hparams.py ..........s.................s...................xx.xxxx.sx....xxx.x.xx..xxs........xxxxxxxxx                                   [ 16%]
tests/test_iter_helpers.py ..........                                                                                                                [ 17%]
tests/test_load.py ..ss.ssss.ss....sss.s.ss..sss...............                                                                                      [ 20%]
tests/test_loss.py ............xxxxxxXXXXXX............                                                                                              [ 22%]
tests/test_model_registry.py ............                                                                                                            [ 23%]
tests/test_object_store.py .                                                                                                                         [ 23%]
tests/test_pillow_simd.py s                                                                                                                          [ 23%]
tests/test_state.py .                                                                                                                                [ 23%]
tests/test_string_enum.py ....                                                                                                                       [ 24%]
tests/test_surgery.py ..........                                                                                                                     [ 24%]
tests/test_time.py .............                                                                                                                     [ 25%]
tests/algorithms/test_algorithm_registry.py ......................                                                                                   [ 27%]
tests/algorithms/test_augmentations_functional.py ....................................................................................               [ 33%]
tests/algorithms/test_blurpool.py ..................................................................                                                 [ 37%]
tests/algorithms/test_blurpool_layers.py ............................................................................................                [ 44%]
tests/algorithms/test_channels_last.py ..........                                                                                                    [ 44%]
tests/algorithms/test_colout.py ...................................................                                                                  [ 48%]
tests/algorithms/test_cutmix.py ..........                                                                                                           [ 48%]
tests/algorithms/test_cutout.py ..............................................................................................                       [ 55%]
tests/algorithms/test_factorize_algorithm.py ............                                                                                            [ 56%]
tests/algorithms/test_factorize_core.py ................................                                                                             [ 58%]
tests/algorithms/test_factorized_modules.py ................................................................................                         [ 64%]
tests/algorithms/test_ghost_batchnorm.py ....xx.................................................                                                     [ 67%]
tests/algorithms/test_label_smoothing.py .............................................................                                               [ 72%]
tests/algorithms/test_layer_freezing.py ...                                                                                                          [ 72%]
tests/algorithms/test_mixup.py ....                                                                                                                  [ 72%]
tests/algorithms/test_progressive_resizing.py .................................................                                                      [ 76%]
tests/algorithms/test_selective_backprop.py .......x......................                                                                           [ 78%]
tests/algorithms/test_squeeze_excite.py .....                                                                                                        [ 78%]
tests/algorithms/test_stochastic_depth.py .................................                                                                          [ 80%]
tests/callbacks/test_callbacks.py ........................                                                                                           [ 82%]
tests/callbacks/test_grad_monitor.py ..                                                                                                              [ 82%]
tests/callbacks/test_memory_monitor.py .                                                                                                             [ 82%]
tests/callbacks/test_speed_monitor.py .                                                                                                              [ 82%]
tests/datasets/test_add_dataset_transform.py .......                                                                                                 [ 83%]
tests/datasets/test_c4.py ssss                                                                                                                       [ 83%]
tests/datasets/test_dataset_utils.py ..                                                                                                              [ 83%]
tests/datasets/test_segmentation_transforms.py .......                                                                                               [ 84%]
tests/datasets/test_synthetic_data.py .s.......s..                                                                                                   [ 85%]
tests/datasets/test_synthetic_lm_data.py ......                                                                                                      [ 85%]
tests/loggers/test_file_logger.py ...                                                                                                                [ 85%]
tests/loggers/test_in_memory_logger.py ..                                                                                                            [ 85%]
tests/loggers/test_logger.py .                                                                                                                       [ 85%]
tests/loggers/test_object_store_logger.py ...                                                                                                        [ 86%]
tests/loggers/test_progress_bar_logger.py .                                                                                                          [ 86%]
tests/loggers/test_wandb_logger.py .                                                                                                                 [ 86%]
tests/metrics/test_metrics.py .                                                                                                                      [ 86%]
tests/metrics/test_nlp_metrics.py ......................                                                                                             [ 87%]
tests/profiler/test_json_trace_handler.py Fatal Python error: Segmentation fault

Thread 0x00007fb39d949700 (most recent call first):
  File "/opt/conda/envs/jax/lib/python3.8/threading.py", line 306 in wait
  File "/opt/conda/envs/jax/lib/python3.8/threading.py", line 558 in wait
  File "/opt/conda/envs/jax/lib/python3.8/site-packages/tqdm/_monitor.py", line 60 in run
  File "/opt/conda/envs/jax/lib/python3.8/threading.py", line 932 in _bootstrap_inner
  File "/opt/conda/envs/jax/lib/python3.8/threading.py", line 890 in _bootstrap

Thread 0x00007fb3a77ed700 (most recent call first):
<no Python frame>

Current thread 0x00007fb4f62744c0 (most recent call first):
  File "/opt/conda/envs/jax/lib/python3.8/site-packages/torch/autograd/profiler.py", line 238 in export_chrome_trace
  File "/opt/conda/envs/jax/lib/python3.8/site-packages/torch/profiler/profiler.py", line 121 in export_chrome_trace
  File "/workspace/composer/composer/profiler/torch_profiler.py", line 209 in handler_fn
  File "/opt/conda/envs/jax/lib/python3.8/site-packages/torch/profiler/profiler.py", line 487 in _trace_ready
  File "/opt/conda/envs/jax/lib/python3.8/site-packages/torch/profiler/profiler.py", line 493 in _transit_action
  File "/opt/conda/envs/jax/lib/python3.8/site-packages/torch/profiler/profiler.py", line 479 in step
  File "/workspace/composer/composer/profiler/torch_profiler.py", line 245 in batch_end
  File "/workspace/composer/composer/core/callback.py", line 99 in run_event
  File "/workspace/composer/composer/core/engine.py", line 292 in _run_callbacks
  File "/workspace/composer/composer/core/engine.py", line 185 in run_event
  File "/workspace/composer/composer/trainer/trainer.py", line 1087 in _train_loop
  File "/workspace/composer/composer/trainer/trainer.py", line 881 in fit
  File "/workspace/composer/tests/profiler/test_json_trace_handler.py", line 32 in test_json_trace_profiler_handler
  File "/root/.local/lib/python3.8/site-packages/_pytest/python.py", line 192 in pytest_pyfunc_call
  File "/root/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/root/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/root/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/root/.local/lib/python3.8/site-packages/_pytest/python.py", line 1761 in runtest
  File "/root/.local/lib/python3.8/site-packages/_pytest/runner.py", line 166 in pytest_runtest_call
  File "/root/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/root/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/root/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/root/.local/lib/python3.8/site-packages/_pytest/runner.py", line 259 in <lambda>
  File "/root/.local/lib/python3.8/site-packages/_pytest/runner.py", line 338 in from_call
  File "/root/.local/lib/python3.8/site-packages/_pytest/runner.py", line 258 in call_runtest_hook
  File "/root/.local/lib/python3.8/site-packages/_pytest/runner.py", line 219 in call_and_report
  File "/root/.local/lib/python3.8/site-packages/_pytest/runner.py", line 130 in runtestprotocol
  File "/root/.local/lib/python3.8/site-packages/_pytest/runner.py", line 111 in pytest_runtest_protocol
  File "/root/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/root/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/root/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/root/.local/lib/python3.8/site-packages/_pytest/main.py", line 347 in pytest_runtestloop
  File "/root/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/root/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/root/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/root/.local/lib/python3.8/site-packages/_pytest/main.py", line 322 in _main
  File "/root/.local/lib/python3.8/site-packages/_pytest/main.py", line 268 in wrap_session
  File "/root/.local/lib/python3.8/site-packages/_pytest/main.py", line 315 in pytest_cmdline_main
  File "/root/.local/lib/python3.8/site-packages/pluggy/_callers.py", line 39 in _multicall
  File "/root/.local/lib/python3.8/site-packages/pluggy/_manager.py", line 80 in _hookexec
  File "/root/.local/lib/python3.8/site-packages/pluggy/_hooks.py", line 265 in __call__
  File "/root/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 164 in main
  File "/root/.local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187 in console_main
  File "/root/.local/lib/python3.8/site-packages/pytest/__main__.py", line 5 in <module>
  File "/opt/conda/envs/jax/lib/python3.8/runpy.py", line 87 in _run_code
  File "/opt/conda/envs/jax/lib/python3.8/runpy.py", line 194 in _run_module_as_main
make: *** [Makefile:30: test] Segmentation fault (core dumped)
```

### PR DESCRIPTION
**Pull request by bandish-shah**
* Adds PyTorch 1.11 + CUDA 11.3 and CPU Docker images to build matrix
* Updates README
* Fixes #847

### CODE REVIEW

**Review by moinnadeem — APPROVED** [review]
LGTM!

**Comment by abhi-mosaic** [comment]
@bandish-shah Do we need the MMCV_TORCH_VERSION specified too? Sounded like @Landanjs may have had some issue with that?

**Comment by Landanjs** [comment]
Could I test the image `mosaicml/pytorch:1.11.0_cu113-python3.9-ubuntu20.04`? I can see if mmcv installs

**Comment by bandish-shah** [comment]
> @bandish-shah Do we need the MMCV_TORCH_VERSION specified too? Sounded like @Landanjs may have had some issue with that?

I'm only adding Torch 1.11 in the `mosaicml/pytorch` image at the moment.  We only specify `MMCV_TORCH_VERSION` for the `mosaicml/pytorch_vision` image.  Does this mean you want a version of that image with Torch 1.11 as well?

**Review by abhi-mosaic — APPROVED** [review]
LGTM! Adding just `mosaicml/pytorch` first and allowing researchers to test, make additional requests later, makes sense to me.

**Pull request merged**
