### PR TITLE
Move ffcv up in test order

### PR DESCRIPTION
**Pull request by dskhudia**
# What does this PR do?

~~Randomize the order of pytest to catch errors that may work if the tests are run in the same order.~~

Move the test up in order so that it passes. Don't ask me why!!

### CODE REVIEW

**Comment by mvpatel2000** [comment]
Can we fix the ones failing rn that are deterministically failing first?

**Comment by dskhudia** [comment]
ffcv test is not deterministically failing for me. It passes on local run.

**Comment by dakinggg** [comment]
So, I agree with the sentiment of this change, but I'm a little worried that we may have a number of non deterministic issues and will spend a significant amount of time debugging them on unrelated PRs. Is there any way we can de risk that? Like, should someone spend a few days just trying different random orders and fixing anything that pops up?

**Comment by dskhudia** [comment]
@dakinggg we don't have to merge this now but eventually do something like this to make testing more robust. Currently I want to see if the test_ffcv failure goes away with this.

**Comment by dakinggg** [comment]
Sounds good :+1:

**Comment by dskhudia** [comment]
>  non deterministic issues and will spend a significant amount of time debugging them on unrelated PRs.

BTW this is more one time effort than ongoing effort.

**Comment by dakinggg** [comment]
> > non deterministic issues and will spend a significant amount of time debugging them on unrelated PRs.
> 
> BTW this is more one time effort than ongoing effort.

Absolutely :)

**Comment by dskhudia** [comment]
Ignore any updates to this PR. This is just to fix the failing test.

**Review by bandish-shah — APPROVED** [review]
Super bizarre but LGTM.

**Pull request merged**
