### PR TITLE
Add Precision Contexts

### PR DESCRIPTION
**Pull request by mvpatel2000**
As title. Was causing problems with methods which require certain precisions.

### CODE REVIEW

**Comment by dskhudia** [comment]
LGTM! Could you add a test for it?

**Review by ravi-mosaicml — COMMENTED** [review]
Code LGTM, though will defer to @dskhudia  or @abhi-mosaic for approval -- they're the precision masters. Agree having a test case would be nice, especially if there was an error beforehand. Take a look at the existing precision test case which measure memory.

**Comment by mvpatel2000** [comment]
Tests on dev 
image

**Review by dskhudia — APPROVED** [review]

**Comment by mvpatel2000** [comment]
@dskhudia looks like tests are failing in CI because the percentage memory usage w precision is only ~85%. On an interactive instance, I'm seeing ~65%. I bumped up thresholds from 70% to 90% for predict/eval, but I don't want to merge unless you think this seems fine with you.

**Comment by dskhudia** [comment]
> @dskhudia looks like tests are failing in CI because the percentage memory usage w precision is only ~85%. On an interactive instance, I'm seeing ~65%. I bumped up thresholds from 70% to 90% for predict/eval, but I don't want to merge unless you think this seems fine with you.

Is there a difference between the number of GPUs used on CI vs interactive instance?

**Pull request merged**
