### PR TITLE
Adding checkpoint backwards compatibility tests after 0.23.0 release

### PR DESCRIPTION
**Pull request by bigning**
# What does this PR do?

Following the release processing doc, this is the last step to add checkpoint backward compatibility tests

Daily test: https://github.com/mosaicml/composer/actions/runs/9407180074

### CODE REVIEW

**Review by eracah — APPROVED** [review]

**Review by snarayan21 — COMMENTED** [review]
Can you run dailies and make sure they pass before merging this? And it would be helpful to link the daily test run in a comment

**Review by j316chuck — APPROVED** [review]

**Review by mvpatel2000 — APPROVED** [review]
LGTM. Agree with Saaketh, can we fire off dailies to verify?

**Comment by bigning** [comment]
@mvpatel2000 , @snarayan21  sounds good. I will fire Daily test after the CI issues are resolved.

**Comment by bigning** [comment]
> Can you run dailies and make sure they pass before merging this? And it would be helpful to link the daily test run in a comment

The daily test indeed failed `test_fsdp_load_old_checkpoint`. It seems expected because 2.1/2.3 can't load checkpoint saved by 2.3. I see it skipped composer 0.22.0. I guess I should do a[ similar change here](https://github.com/mosaicml/composer/pull/3377/files#diff-b256bc9e5648c081bc432ccaa721ffea5d422c6574883bbabf9cef61ef991ae9L512).   @snarayan21 , is my understanding correct ? I started a new daily test.

**Pull request merged**
