### PR TITLE
Proofread Custom Speedup Method Notebook; Pre-Commit Fixes

### PR DESCRIPTION
**Pull request by mcneela**
* Proofread Custom Speedup Method Notebook 
* Remove empty cells in the pre-commit hook
* Keep notebook `language_info` metadata so pygments highlighting will work on the docs site

### CODE REVIEW

**Comment by mcneela** [comment]
@hanlint Do we want to merge this? The updates to the notebook were pretty straightforward.

**Comment by hanlint** [comment]
@mcneela I can't quite see the `diff` in github, was `clean-notebooks` run?

**Comment by mcneela** [comment]
> @mcneela I can't quite see the `diff` in github, was `clean-notebooks` run?

Yes, I just tried rerunning `clean-notebooks` and no changes were produced. Maybe just give it a quick visual inspection in jupyter directly?

**Comment by ravi-mosaicml** [comment]
This diff was large as I removed the image from the notebook on dev (and renamed the file). I updated dev into this branch to fix the example. Need to double check that the example works on cpu and gpu; then it should be good to merge.

**Review by ravi-mosaicml — APPROVED** [review]
LGTM

**Pull request merged**
