### PR TITLE
version bump to 0.24.0

### PR DESCRIPTION
**Pull request by eracah**
bump version

### CODE REVIEW

**Comment by antoinebrl** [comment]
Hello! Should this version be compatible with torch 2.4?

**Comment by mvpatel2000** [comment]
> Hello! Should this version be compatible with torch 2.4?

Unfortunately, no -- there is some complexity we're hitting with bump and monkeypatches. We're going to do a follow-up release that will include it CC: @j316chuck

**Comment by antoinebrl** [comment]
@mvpatel2000 Thanks for sharing the details! 👍  We will adjust our plan accordingly.

**Comment by snarayan21** [comment]
Taking over this PR from @eracah.

@mvpatel2000 @bigning one thing to note -- I'm completely removing `create_fsdp_config` function since the functionality has been completely deprecated. Just wanted to call attention to that and make sure it's good with y'all.

Running dailies: https://github.com/mosaicml/composer/actions/runs/10516433172

**Comment by snarayan21** [comment]
Closing in favor of #3570

**Pull request closed without merging**
