### PR TITLE
update model token embeddings according to tokenizer len

### LINKED ISSUE #1492: HuggingFace model should update word embeddings dimension according to tokenizer
** To reproduce

Right now if I call 

```
model = transformers.AutoModelForCausalLM.from_pretrained('bigscience/bloom-560m')
tokenizer = transformers.AutoTokenizer.from_pretrained('gpt2')

model = HuggingFaceModel(model=model, tokenizer=tokenizer)
```

The bloom model will have a [250880, 1024] dim word embedding matrix and a vocab size of 250880 even though a gpt2 tokenizer with vocab size of 50257 is used.

## Expected behavior

The class HuggingFaceModel needs to update word embedding matrix if a tokenizer is supplied.

### PR DESCRIPTION
**Pull request by ananyahjha93**
tell me if I need to add any tests for this. Closes #1492

### CODE REVIEW

**Review by moinnadeem — COMMENTED** [review]
@ananyahjha93 Great contribution! 

I want to be careful when we sliently change the model without the user necessarily knowing (to help avoid user error): can you precede this with a `log.warning(f"The number of tokens in the tokenizer and the number of tokens in the model are different. Resizing the model tokenizer to from {config.vocab_size} to {len(tokenizer}."` that gets printed if `config.vocab_size != len(tokenizer)`? 

That way, if this is unexpected (or undesired), the user at least knows. Does that make sense?

Happy to give an LGTM once that is in there!

**Comment by ananyahjha93** [comment]
@moinnadeem done!

**Comment by moinnadeem** [comment]
@ananyahjha93 Awesome, thanks1 One last part of the requested change that was unaddressed:
> that gets printed if `config.vocab_size != len(tokenizer)`?

As it currently stands, the user would be seeing this if the `config.vocab_size==len(tokenizer)`, which could lead to confusion. We should only print the warning (and resize) when the sizes are different. Does this make sense? Let me know if the motivation isn't clear

Thanks for the PR btw, I've been meaning to do this 😅

**Comment by ananyahjha93** [comment]
@moinnadeem sorry, missed that part, its a bit early in the morning here in Seattle 😝 
fixed it

**Review by moinnadeem — APPROVED** [review]
Hahaha, I'm in PST as well so I know the feeling 😅

Great work! Congratulations on your first commit to Composer! 😎🤩

**Comment by ananyahjha93** [comment]
thanks!

**Pull request merged**
