### PR TITLE
Clarify DWD defaults

### PR DESCRIPTION
**Pull request by abhi-mosaic**
Addresses #409

### CODE REVIEW

**Comment by moinnadeem** [comment]
Thanks for getting to this so quickly! 

Two thoughts:
1. The current approach still requires the user to Google the current defaults used in PyTorch. I would strongly prefer to just have defaults in our docstring, rather than pass that indirection to our users.
2. If we MUST pass that indirection to our users, we should hyperlink the SGD / AdamW:

`Argument defaults are copied from `torch.optim.SGD`.` in order to make it convenient. 

I have a reasonable preference for #1, but would be willing to hear an argument for #2.

**Comment by abhi-mosaic** [comment]
I'm a bit confused, doesn't our docstring already include the defaults, as well as hyperlinks to torch's SGD and AdamW?

**Comment by hanlint** [comment]
I think what is confusing @moinnadeem is that the first method is not `__init__`, where the defaults are.

**Comment by hanlint** [comment]
Updating and merging after tests pass.. @moinnadeem feel free to reopen if the change, and the comments don't address the issue. But the DWD do seem documented in both the code (`__init__`) and the docstrings.

**Pull request merged**
