### PR TITLE
[XS] use correct package name in error messages

### PR DESCRIPTION
**Pull request by jbloxham**

### CODE REVIEW

**Review by mvpatel2000 — APPROVED** [review]

**Review by moinnadeem — APPROVED** [review]
LGTM!

**Review by mvpatel2000 — CHANGES_REQUESTED** [review]
```pip install mosaicml[nlp]
zsh: no matches found: mosaicml[nlp]```

**Comment by moinnadeem** [comment]
@mvpatel2000 Can you try `pip install 'mosaicml[nlp]'`?

**Comment by mvpatel2000** [comment]
> @mvpatel2000 Can you try `pip install "mosaicml[nlp]"`?

Works!

**Comment by jbloxham** [comment]
Good catch @mvpatel2000 ! And thanks @moinnadeem for the fix!

**Review by mvpatel2000 — APPROVED** [review]

**Pull request merged**
