### PR TITLE
Add ls to object stores

### PR DESCRIPTION
**Pull request by dakinggg**
# What does this PR do?
Adds `list_objects` support to libcloud, s3, and oci object stores. We don't have a setup to use sftp object store so I'm leaving that unimplemented for now. 

We don't have great object store unit tests, so I tried to maintain the current standard, but did not improve it. That is, I followed the mocking already setup for oci object store, used the local storage for libcloud, and did not add a unit test for s3.

We also have inconsistent support for specifying a prefix to the constructor. s3 supports it, libcloud doesn't, and oci accepts the arg but doesn't seem to use it (although I do use it in the new `list_objects`)

# What issue(s) does this change relate to?
Closes [CO-2236](https://mosaicml.atlassian.net/browse/CO-2236)

# Manual test
```
printing out the total number of objects for each case

listing prefixes that don't exist
s3: 0
s3 via libcloud: 0
oci: 0

listing daniel prefix specified to list_objects
s3: 106052
s3 via libcloud: 106052
oci: 373740

listing daniel prefix specified to constructor (same numbers as above)
s3: 106052
oci: 373740

listing daniel/checkpoints prefix, daniel specified to constructor, checkpoints specified to list_objects
s3: 18
oci: 311

listing root in a different bucket
s3: 21525
s3 via libcloud: 21525
oci: 80
```

# Before submitting
- [x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [x] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [x] Did you update any related docs and document your change?
- [x] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [x] Did you run the tests locally to make sure they pass?
- [x] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

[CO-2236]: https://mosaicml.atlassian.net/browse/CO-2236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mvpatel2000 — COMMENTED** [review]
LGTM but will also want approval from @eracah

**Comment by dakinggg** [comment]
Manual test is in the description, do you mean something else?

**Review by eracah — COMMENTED** [review]
looks good. can you add a true output to the manual tests (not just len of the output)?

**Comment by dakinggg** [comment]
@eracah It worked, I just didn't want to copy paste our object store paths into the PR

**Review by eracah — APPROVED** [review]
LGTM

**Pull request merged**
