### PR TITLE
Add loss_dict keyword to closure lambda function

### PR DESCRIPTION
**Pull request by Landanjs**
# What does this PR do?

SAM without gradient scaling is broken when using a dictionary of losses. This is due to not specifying the `loss_dict` arg in the lambda argument.

# What issue(s) does this change relate to?
Closes [CO-1746](https://mosaicml.atlassian.net/browse/CO-1746)

# Before submitting
- [x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

[CO-1746]: https://mosaicml.atlassian.net/browse/CO-1746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by dakinggg — COMMENTED** [review]
Could you add a test that would catch this?

**Comment by Landanjs** [comment]
Yes, but I won't be able to get to it until Friday at the latest

**Comment by dakinggg** [comment]
No worries, next composer release isn't for a while.

**Comment by Landanjs** [comment]
It only took me 4 months and a week, but a test is written

**Review by mvpatel2000 — APPROVED** [review]

**Pull request merged**
