### PR TITLE
Print the stdout/stderr of the crashing process

### PR DESCRIPTION
**Pull request by ravi-mosaicml**
Fix the launcher script to always print the stdout/stderr of the crashing process. To do so, the stdout and stderr must always be saved to a file. Then, the launcher script can read from the stdout and stderr files to print these to the terminal.

### CODE REVIEW

**Comment by hanlint** [comment]
@Landanjs can you verify that this fixes the issue?

**Comment by Landanjs** [comment]
In my example, the stdout from each process is now printed to terminal which is helpful! But it is difficult to parse the stdout though since each process prints the training configuration. On VScode, the full logs does not fit on my terminal, so I can only see processes 4-6

Is there anyway to print the stdout from the crashing process or to only print the traceback?

**Comment by Landanjs** [comment]
We decided to only print the configuration on rank 0 which should reduce the length of the stdout

**Review by Landanjs — APPROVED** [review]
Can't comment on the code, but I think the functionality is a good first step! It can still be difficult to parse the logs, but at least the necessary info is provided.

 In the future, it would be good to explore better ways of conveying traceback info.

**Pull request merged**
