### PR TITLE
Fix LOCAL_WORLD_SIZE in pytest

### PR DESCRIPTION
**Pull request by rishab-partha**
# What does this PR do?

Fix CI/CD by changing LOCAL_WORLD_SIZE

# What issue(s) does this change relate to?

Fixing CI/CD

### CODE REVIEW

**Comment by mvpatel2000** [comment]
Should we just wait for cloud to fix? I think this failing is a good test for platform broken?

**Comment by rishab-partha** [comment]
@mvpatel2000 Cloud has already fixed, it's an issue on our end w.r.t. to default dist values.

**Comment by dakinggg** [comment]
@mvpatel2000 This is because the ci is trying to run `make test-gpu` (note: _not_ `make test-dist-gpu`) with `LOCAL_WORLD_SIZE=2`, which is invalid and causes `initialize_dist` to fail. @rishab-partha I think we should actually fix this in the makefile, not the `mcli_pytest.py` file. so `make test` and `make test-gpu` should set the `LOCAL_WORLD_SIZE` to 1. wdyt?

**Comment by rishab-partha** [comment]
fixed!

**Review by dakinggg — APPROVED** [review]
@mvpatel2000 will give you a couple hours to see if you want to reject this for some reason, otherwise will merge to unblock CI

**Comment by mvpatel2000** [comment]
Lgtm. Same w foundry

**Pull request merged**
