### PR TITLE
Revert monitored barrier

### PR DESCRIPTION
**Pull request by mvpatel2000**
Disable monitored barrier when gloo fails to initialize

### CODE REVIEW

**Comment by mvpatel2000** [comment]
@ravi-mosaicml  can you just force merge this the tests are flakey and making me sad

**Comment by mvpatel2000** [comment]
Nvm fourth time is the charm

**Comment by mvpatel2000** [comment]
Actually, I think I'll catch initialization errors and then only use monitored barriers when we initialize correctly. This way, we can at least get this feature when not using a lot of GPUs

**Review by ravi-mosaicml — APPROVED** [review]
I'll approve it for now....on my list next week to rip out pytest timeout.

Feel free to leave all the helper functions in, though, and just remove the global initialization and the use of the monitored barrier in the train loop.

**Comment by mvpatel2000** [comment]
Rerequesting review since I'm not disabling anymore, but suppressing gloo instantiation failure as a log error

**Comment by mvpatel2000** [comment]
Hm... I'm getting some issues with NCCL when checking if Gloo setup when using 16 GPUs (works fine with 2)... For now, I'm going to disable the monitored barrier set up and put up a new PR that fixes this. Adjusting auto grad accum is in the works anyways so it'll all be one PR later
```
Traceback (most recent call last):
  File "/composer/examples/run_composer_trainer.py", line 83, in <module>
    _main()
  File "/composer/examples/run_composer_trainer.py", line 48, in _main
    trainer = hparams.initialize_object()
  File "/usr/local/lib/python3.9/dist-packages/composer/trainer/trainer_hparams.py", line 437, in initialize_object
    dist.initialize_dist(device, datetime.timedelta(seconds=self.dist_timeout))
  File "/usr/local/lib/python3.9/dist-packages/composer/utils/dist.py", line 453, in initialize_dist
    all_reduce(gloo_initialization_failure, reduce_operation='MAX')
  File "/usr/local/lib/python3.9/dist-packages/composer/utils/dist.py", line 231, in all_reduce
    dist.all_reduce(tensor, op=reduce_op)
  File "/usr/local/lib/python3.9/dist-packages/torch/distributed/distributed_c10d.py", line 1314, in all_reduce
    work = default_pg.allreduce([tensor], opts)
RuntimeError: [6] is setting up NCCL communicator and retreiving ncclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: Socket Timeout
```

**Pull request merged**
