### PR TITLE
Bert model card

### PR DESCRIPTION
**Pull request by A-Jacobson**
added bert model card focused on pre-training. 

@moinnadeem we discussed skipping info on GLUE for now but if that's important to users perhaps we should mention it?

@bandish-shah want to help me choose an emoji? =)

### CODE REVIEW

**Review by moinnadeem — APPROVED** [review]
LGTM! Thanks for getting to this Austin :)

**Review by moinnadeem — CHANGES_REQUESTED** [review]
Overall LGTM! If we could add more information from the 24H BERT paper, that'd be great.

In particular, we should mention that we disregard the NSP loss, and that after reproducing the original BERT metrics, we train on C4 due to improved performance.
We can include a sentence about C4 in the "Implementation Details" section.

**Review by moinnadeem — APPROVED** [review]
LGTM!

**Comment by bandish-shah** [comment]
I mean I feel like you have to go with a Bert emoji:
https://slackmojis.com/emojis/27743-bert/download

**Pull request merged**
