### PR TITLE
Removed duplicate callbacks

### PR DESCRIPTION
**Pull request by ravi-mosaicml**
The correct pytorch profiler file is `composer/callbacks/pytorch_profiler.py`

### CODE REVIEW

**Review by Averylamp — APPROVED** [review]
lgtm
file is: `composer/callbacks/torch_profiler.py`

**Comment by hanlint** [comment]
@ravi-mosaicml can you also remove `timimg_monitor.py` which is duplicate of the `benchmarker.py` as well?

**Comment by ajaysaini725** [comment]
> @ravi-mosaicml can you also remove `timimg_monitor.py` which is duplicate of the `benchmarker.py` as well?

Actually can we keep `timing_monitor.py` and remove `benchmarker.py` because of #74 which introduces a class called `Benchmarker` that uses `TimingMonitor`? Just trying to avoid a name conflict - open to suggestions for alternate names

**Comment by ravi-mosaicml** [comment]
@ajaysaini725 The `timing_monitor.py` is out of date (Benchmarker is correct). Open to other names though for the what is currently called the benchmarker...perhaps `FastForwarder`?

**Pull request merged**
