### PR TITLE
add stop method

### PR DESCRIPTION
**Pull request by hanlint**
# What does this PR do?

Adds a `state.stop_training()` method for algorithms and callbacks to gracefully stop training (finishing the rest of the events in the current batch and any scheduled evals and epoch ends). The EarlyStopping and MLPerf callback now uses this interface instead of setting the max duration itself.

# Before submitting
- [x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [x] Did you update any related docs and document your change?
- [x] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [x] Did you run the tests locally to make sure they pass?
- [x] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

### CODE REVIEW

**Review by dakinggg — APPROVED** [review]
LGTM

**Review by mvpatel2000 — APPROVED** [review]
It feels a little weird for this to be a state method. I'd expect it to be more like a helper function that accepts a state object as an argument. 

I don't have strong opinions on this though (just a weird vibe lol) and I'm fine with it as is. I don't really have a concrete place I'd want to put it otherwise either, so lgtm.

**Comment by hanlint** [comment]
I agree having it in state is a little weird. Its the indirection --> a method on state stops training but only when coupled with the trainer. `trainer.stop()` is most intutitive, but not accessible from our callbacks and algorithms, so at a bit of loss there. 

I could rename it from `state.stop_training()` to `state.set_duration_to_now` or something but that's pretty verbose.

**Comment by mvpatel2000** [comment]
> I could rename it from `state.stop_training()` to `state.set_duration_to_now` or something but that's pretty verbose.
Let's leave as is. I don't love it, but its good enough imo. A bit weird, but I'd rather make it easy to use

**Pull request merged**
