### PR TITLE
Add composer version state

### PR DESCRIPTION
**Pull request by dakinggg**
# What does this PR do?
Adds composer version to a `metadata` section of the state dict. This will allow us to do compatibility checks in the future, and also debug checkpoints that may be broken.

# What issue(s) does this change relate to?
Is a start to [CO-1428](https://mosaicml.atlassian.net/browse/CO-1428)

# Before submitting
- [x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [x] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [x] Did you update any related docs and document your change?
- [x] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [x] Did you run the tests locally to make sure they pass?
- [x] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

### CODE REVIEW

**Comment by mvpatel2000** [comment]
Can we use https://github.com/mosaicml/composer/blob/6ec677d88ae6b0a912488376232b0082eb929d0d/composer/utils/collect_env.py#L287 instead? more comprehensive

**Review by mvpatel2000 — COMMENTED** [review]
LGTM besides comment on getting more metadata

**Comment by dakinggg** [comment]
Ah, sure, thats reasonable

**Review by eracah — APPROVED** [review]
LGTM

**Review by mvpatel2000 — APPROVED** [review]

**Pull request merged**
