### PR TITLE
Fix CPU dailies

### PR DESCRIPTION
**Pull request by mvpatel2000**
# What does this PR do?

Fix CPU dailies. Runs wandb in offline mode

### CODE REVIEW

**Review by dakinggg — APPROVED** [review]

**Review by snarayan21 — APPROVED** [review]
oh that's v useful

**Comment by b-chu** [comment]
Shouldn't dailies also test integrations with third party providers? We already have some wandb tests as offline

**Comment by mvpatel2000** [comment]
> Shouldn't dailies also test integrations with third party providers? We already have some wandb tests as offline

We don't have keys anymore as we've switched to MLFlow

**Comment by b-chu** [comment]
We should get keys for our team to make sure we can keep supporting wandb integrations

**Pull request merged**
