### PR TITLE
Expose input_names and output_names when exporting to ONNX

### PR DESCRIPTION
**Pull request by antoinebrl**
# What does this PR do?

It is now to configure the name of the input and output nodes of the ONNX graph.

### CODE REVIEW

**Comment by mvpatel2000** [comment]
@antoinebrl  it looks like you have some lint issues. mind fixing those and then we can merge and include this in release?

**Comment by antoinebrl** [comment]
@mvpatel2000 I permuted two lines to make pyright happy.

**Comment by mvpatel2000** [comment]
@antoinebrl  it looks like tests are failing. can you please take a look?

**Comment by antoinebrl** [comment]
I had to update some mocks used in other files. I ran the whole test suite and i can say "it works on my machine" now 😉

**Pull request merged**
