### PR TITLE
Nuke YAHP

### PR DESCRIPTION
**Pull request by hanlint**
This PR removes YAHP from our codebase.

### CODE REVIEW

**Review by bandish-shah — APPROVED** [review]
👍 let's roll!

**Review by mvpatel2000 — APPROVED** [review]
LGTM

**Review by dakinggg — APPROVED** [review]

**Review by eracah — APPROVED** [review]
LGTM. I guess `examples/glue/*` will stay as is and research will modify it?

**Comment by dakinggg** [comment]
@eracah @hanlint no, examples/glue should be removed as well.

**Review by knighton — APPROVED** [review]
:boom:

**Pull request merged**
