### PR TITLE
Update DeepLabv3 pretrained weight interface to work with PyTorch 1.12

### PR DESCRIPTION
**Pull request by Landanjs**
This is supposed to be similar to the ResNet PR here: https://github.com/mosaicml/composer/pull/1262. 

The `is_backbone_pretrained` and `backbone_url` are replaced in favor of `backbone_weights` which uses PyTorch's new multiple weights API. When torchvision is below 0.13, the respective urls for `IMAGENET1K_V1` and `IMAGENET1K_V2` are hardcoded.

For the future, we need a better interface to be able to use arbitrary pre-trained weights i.e. be able to use weights locally or ones stored in the cloud. I just wanted to get a quick fix to use PyTorch 1.12, but will create a jira for this feature

### CODE REVIEW

**Review by hanlint — APPROVED** [review]
lgtm!

**Comment by hanlint** [comment]
Perhaps have someone in vision cc: @A-Jacobson take a quick look.

**Comment by Landanjs** [comment]
I can't interpret why the test failed. Is something abnormal happening or am I missing the failure?

**Review by A-Jacobson — APPROVED** [review]
hey! looks good to me. like the new pytorch weight format much better.

**Pull request merged**
