### PR TITLE
Fix issue with doctest format in some docstring examples

### PR DESCRIPTION
**Pull request by Landanjs**
Fix issue with doctest format in some docstring examples

### CODE REVIEW

**Comment by Landanjs** [comment]
Hmm the doctests are timing out, do we need to call fit? Or should it be able to train in < 2 seconds

**Review by hanlint — APPROVED** [review]
LGTM, thanks! The timeout error looks unrelated to this PR

**Comment by ravi-mosaicml** [comment]
I updated in dev to re-trigger Jenkins; hopefully it will pass.

I also wrote up https://github.com/mosaicml/composer/pull/1272 to hopefully fix this issue for good.

**Review by ravi-mosaicml — APPROVED** [review]
Spot-checked how it looks in the docs build; seems good. Thanks!

**Comment by Landanjs** [comment]
Hmmm, are the timeout issues still unrelated?

**Pull request merged**
