### PR TITLE
Global batch size

### PR DESCRIPTION
**Pull request by mvpatel2000**
# What does this PR do?

Previously, our helper functions to build dataloaders accepted a per device batch size. We've seen users repeatedly mess this up and instead pass global batch size. This PR switches our helper functions to use global batch size, which will make abstractions easier for users. 

As a follow-up, [CO-1428](https://mosaicml.atlassian.net/browse/CO-1428) will check to ensure the same global batch size is used when resuming or otherwise emit a warning.

# What issue(s) does this change relate to?

[CO-1429](https://mosaicml.atlassian.net/browse/CO-1429)

### CODE REVIEW

**Comment by mvpatel2000** [comment]
Requesting from Hanlin as the initial versions were constructed based on post-YAHP epics iirc

**Review by hanlint — COMMENTED** [review]
LGTM -- cc: @codestar12 and the hydra repositories

Do any of the examples need to change?

**Comment by codestar12** [comment]
looks good to me. This should simplify the hydra trainer as I won't need to manually apply this anymore.

**Review by codestar12 — COMMENTED** [review]
LGTM. Do we still have plans to allow trainer to accept a factory function for building a dataset?

**Comment by mvpatel2000** [comment]
> LGTM. Do we still have plans to allow trainer to accept a factory function for building a dataset?

Discussed offline, answer is no for now

**Review by knighton — APPROVED** [review]
Let's Get That Merged

**Pull request merged**
