### PR TITLE
Added colab example

### LINKED ISSUE #78: Add Colab Example
* Add Example Jupyter notebook to the examples folder
* Add "Open in Colab" to the README.md

### PR DESCRIPTION
**Pull request by ravi-mosaicml**
Closes #78

This PR depends on #68

### CODE REVIEW

**Comment by jbloxham** [comment]
When I tried running this I got an error on `!pip install mosaicml`:

```
ERROR: Could not find a version that satisfies the requirement mosaicml (from versions: none)
ERROR: No matching distribution found for mosaicml
```

**Comment by Averylamp** [comment]
> When I tried running this I got an error on `!pip install mosaicml`:
> 
> ```
> ERROR: Could not find a version that satisfies the requirement mosaicml (from versions: none)
> ERROR: No matching distribution found for mosaicml
> ```

I think make sure you're using `>=3.8` for python, as `3.7` support hasn't been officially released to pypi yet.  That's my guess

**Comment by jbloxham** [comment]
Makes sense - I'll revisit this PR later then.

**Comment by Averylamp** [comment]
If possible, would love to have an integration test on this example.  I think it'd likely be very useful to make sure out examples don't go out of date

**Comment by ravi-mosaicml** [comment]
@Averylamp great point, added a test.

**Review by Averylamp — APPROVED** [review]
Lgtm

**Pull request merged**
