### PR TITLE
Fix FSDP ckpt by filtering User Waring

### PR DESCRIPTION
**Pull request by j316chuck**
# What does this PR do?
Fix FSDP ckpt by filtering User Warning

# What issue(s) does this change relate to?
Fix failing dailies
https://github.com/mosaicml/composer/actions/runs/9231304954

### CODE REVIEW

**Review by snarayan21 — COMMENTED** [review]
@j316chuck Can you run the daily tests on this branch and see if they pass now? will approve after that

**Comment by j316chuck** [comment]
@snarayan21 here ya go: https://github.com/mosaicml/composer/actions/runs/9231304954

**Review by mvpatel2000 — APPROVED** [review]

**Comment by mvpatel2000** [comment]
Hm automerge was on so it merged even though its not fixed on linked dailies...

**Comment by snarayan21** [comment]
sad...but I don't think the error is related to this PR, it seems related to the TP PR @mvpatel2000

**Comment by j316chuck** [comment]
@mvpatel2000 I think it fixed the UserWarning but now we are in shardedTensor failure land

**Pull request merged**
