### PR TITLE
Yahp v0.1.3

### PR DESCRIPTION
**Pull request by mvpatel2000**
New YAHP just dropped 👀 

Commit history is long because I used this branch to test compatibility pre-release.

### CODE REVIEW

**Comment by mvpatel2000** [comment]
This looks like same failure as this conda [issue](https://github.com/conda/conda/issues/11442). Conda has an open PR to resolve [it](https://github.com/conda/conda/pull/11612).

I guess I'll just retry tests and see if its transient...

**Comment by mvpatel2000** [comment]
Moving discussion offline to see how to proceed with issues described in previous comment

**Review by ravi-mosaicml — APPROVED** [review]
Approving; though make sure tests pass before merging.

**Comment by mvpatel2000** [comment]
Testing if it passes otherwise

**Comment by mvpatel2000** [comment]
As this is being blocked by Conda issues, we're temporarily disabling the Conda build (download count is pretty low for Conda anyways). The current workaround for end-users is to use `mamba install` instead of `conda install`. Once https://github.com/conda/conda/pull/11612 is merged, we'll re-enable Conda builds

**Pull request merged**
