### PR TITLE
Update types to follow PEP 585

### PR DESCRIPTION
**Pull request by b-chu**
# What does this PR do?
commit-id:ecb54855

---

**Stack**:
- #2698
- #2697 ⬅
- #2696
- #2695

⚠️ *Part of a stack created by [spr](https://github.com/ejoffe/spr). Do not merge manually using the UI - doing so may have unexpected results.*

# What issue(s) does this change relate to?

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

### CODE REVIEW

**Review by mvpatel2000 — COMMENTED** [review]
Should we do this everywhere...? Can we just use a replace tool on entire codebase...?

**Comment by b-chu** [comment]
Yes, but incremental changes seem safer? If someone wants to take up the lift of doing it on the entire codebase and validating, I'm happy to close the PR.

**Review by mvpatel2000 — APPROVED** [review]
LGTM. Fair enough for marginal

**Review by mvpatel2000 — CHANGES_REQUESTED** [review]
Breaks python 3.8 (unit tests will catch when they run)

**Review by mvpatel2000 — APPROVED** [review]
Brian claims it works with future

**Pull request merged**
