### PR TITLE
Stripping whitespaces as default for QATask ICL eval

### PR DESCRIPTION
**Pull request by ksreenivasan**
Running tests to confirm it doesn't break any other evals.

# What does this PR do?

If normalization is off (like in gsm8k), leading/trailing whitespaces can cause mismatch which leads to low accuracy even when the model gets the answer right. Adding a `.strip()` to be default behavior here.

# Before submitting
- [x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [x] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [x] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

### CODE REVIEW

**Comment by ksreenivasan** [comment]
Running gauntlet on Llama-2 and OPT to make sure things run smoothly. Track run at `llama-opt-gauntlet-eval-H9qpEW`. Numbers so far look right to me:
```| model_name               |   core_average |   world_knowledge |   commonsense_reasoning |   language_understanding |   symbolic_problem_solving |   reading_comprehension |
|:-------------------------|---------------:|------------------:|------------------------:|-------------------------:|---------------------------:|------------------------:|
| meta-llama/Llama-2-7b-hf |         0.4165 |          0.510723 |                0.355324 |                 0.656446 |                   0.224974 |                0.335033 |
```

Please review and merge.
cc @bmosaicml @dakinggg

**Comment by maxisawesome** [comment]
Should we also strip the answers as well?

**Comment by maxisawesome** [comment]
@ksreenivasan I feel if we apply strip to the outputs, we should also apply them to the labels. I agree that most processed datasets will not leave whitespace before or after the official answer, but this feels more internally consistent. Other than that I approve

**Review by maxisawesome — APPROVED** [review]
lesgo

**Review by dakinggg — APPROVED** [review]
Approving from composer eng, relying on Max for the correctness review

**Pull request merged**
