### PR TITLE
Upgrade docker images to `torch==1.13.1`

### PR DESCRIPTION
**Pull request by abhi-mosaic**
# What does this PR do?

Upgrade `mosaicml/...` docker images to torch==1.13.1.

### CODE REVIEW

**Comment by abhi-mosaic** [comment]
It looks like ffcv==0.0.3 tries to install `sklearn` rather than `scikit-learn`... is there any hope of them fixing this upstream? Or should we just use the envvar override: `SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True`?

```
18:01:30  Collecting ffcv==0.0.3
18:01:30    Downloading ffcv-0.0.3.tar.gz (53 kB)
18:01:30       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.6/53.6 kB 9.9 MB/s eta 0:00:00
18:01:30    Preparing metadata (setup.py): started
18:01:30    Preparing metadata (setup.py): finished with status 'done'
18:01:30  Collecting opencv-python<4.6,>=4.5.5.64
18:01:30    Downloading opencv_python-4.5.5.64-cp36-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (60.5 MB)
18:01:31       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.5/60.5 MB 208.7 MB/s eta 0:00:00
18:01:31  Collecting numba<0.56,>=0.55.0
18:01:31    Downloading numba-0.55.2-cp310-cp310-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (3.4 MB)
18:01:31       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 143.3 MB/s eta 0:00:00
18:01:31  Collecting mmsegmentation<0.23,>=0.22.0
18:01:31    Downloading mmsegmentation-0.22.1-py3-none-any.whl (753 kB)
18:01:31       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 753.8/753.8 kB 152.6 MB/s eta 0:00:00
18:01:31  Collecting terminaltables
18:01:31    Downloading terminaltables-3.1.10-py2.py3-none-any.whl (15 kB)
18:01:31  Collecting pytorch_pfn_extras
18:01:31    Downloading pytorch-pfn-extras-0.6.3.tar.gz (134 kB)
18:01:31       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 134.4/134.4 kB 349.4 MB/s eta 0:00:00
18:01:31    Installing build dependencies: started
18:01:33    Installing build dependencies: finished with status 'done'
18:01:33    Getting requirements to build wheel: started
18:01:33    Getting requirements to build wheel: finished with status 'done'
18:01:33    Preparing metadata (pyproject.toml): started
18:01:34    Preparing metadata (pyproject.toml): finished with status 'done'
18:01:34  Collecting fastargs
18:01:34    Downloading fastargs-1.2.0.tar.gz (12 kB)
18:01:34    Preparing metadata (setup.py): started
18:01:34    Preparing metadata (setup.py): finished with status 'done'
18:01:34  Collecting matplotlib
18:01:34    Downloading matplotlib-3.6.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.8 MB)
18:01:34       ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.8/11.8 MB 68.0 MB/s eta 0:00:00
18:01:34  Collecting sklearn
18:01:34    Downloading sklearn-0.0.post1.tar.gz (3.6 kB)
18:01:34    Preparing metadata (setup.py): started
18:01:35    Preparing metadata (setup.py): finished with status 'error'
18:01:35    error: subprocess-exited-with-error
18:01:35    
18:01:35    × python setup.py egg_info did not run successfully.
18:01:35    │ exit code: 1
18:01:35    ╰─> [18 lines of output]
18:01:35        The 'sklearn' PyPI package is deprecated, use 'scikit-learn'
18:01:35        rather than 'sklearn' for pip commands.
18:01:35        
18:01:35        Here is how to fix this error in the main use cases:
18:01:35        - use 'pip install scikit-learn' rather than 'pip install sklearn'
18:01:35        - replace 'sklearn' by 'scikit-learn' in your pip requirements files
18:01:35          (requirements.txt, setup.py, setup.cfg, Pipfile, etc ...)
18:01:35        - if the 'sklearn' package is used by one of your dependencies,
18:01:35          it would be great if you take some time to track which package uses
18:01:35          'sklearn' instead of 'scikit-learn' and report it to their issue tracker
18:01:35        - as a last resort, set the environment variable
18:01:35          SKLEARN_ALLOW_DEPRECATED_SKLEARN_PACKAGE_INSTALL=True to avoid this error
18:01:35        
18:01:35        More information is available at
18:01:35        https://github.com/scikit-learn/sklearn-pypi-package
18:01:35        
18:01:35        If the previous advice does not cover your use case, feel free to report it at
18:01:35        https://github.com/scikit-learn/sklearn-pypi-package/issues/new
18:01:35        [end of output]
18:01:35    
18:01:35    note: This error originates from a subprocess, and is likely not a problem with pip.
18:01:35  error: metadata-generation-failed
```

**Comment by abhi-mosaic** [comment]
Made a request here, but we should probably not wait for a whole new release: https://github.com/libffcv/ffcv/issues/274

**Comment by dakinggg** [comment]
I think it is ok to set the env var for now

**Review by mvpatel2000 — APPROVED** [review]
Hm... why is this only failing now? that's weird

**Pull request merged**
