### PR TITLE
Pin torchmetrics

### PR DESCRIPTION
**Pull request by mvpatel2000**
# What does this PR do?

It seems the newest torchmetrics causes backwards compatibility issues. Pinning and we will fix in following major release

# What issue(s) does this change relate to?

[CO-1916](https://mosaicml.atlassian.net/browse/CO-1916)

[CO-1916]: https://mosaicml.atlassian.net/browse/CO-1916?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by bandish-shah — APPROVED** [review]
LGTM

**Comment by superherointj** [comment]
Release v0.14.1 has happened. Should this pin still exist?

**Comment by superherointj** [comment]
> It seems the newest torchmetrics causes backwards compatibility issues. Pinning and we will fix in following major release

Release [v0.14.0](https://github.com/mosaicml/composer/releases/tag/v0.14.0) happened two weeks ago.
Is this issue solved [for unpinning]?

**Comment by mvpatel2000** [comment]
@superherointj This should be fixed [here](https://github.com/mosaicml/composer/pull/2116), but it seems we forgot to raise the pin. I'll confirm and fix this next week -- the person who worked on this is on vacation. If this is blocking you, it should be fine to force install a newer version. Please let me know if you hit any issues!

**Comment by mvpatel2000** [comment]
@superherointj we've confirmed and raised the pin in dev, and it should be gone in the next release. If you hit any issues force installing in the mean time, please let me know!

**Pull request merged**
