### PR TITLE
StreamingDataset: make remote optional, attempt to prettify docstrings.

### PR DESCRIPTION
**Pull request by knighton**

### CODE REVIEW

**Review by ravi-mosaicml — COMMENTED** [review]
Thanks for cleaning this up. Please double-check the built docs for formatting: https://mosaicml-composer--1220.com.readthedocs.build/en/1220/api_reference/composer.datasets.streaming.dataset.html#module-composer.datasets.streaming.dataset

**Review by abhi-mosaic — APPROVED** [review]
Assuming these docstrings meet all the formatting guide stuff @ravi-mosaicml? This looks good to me. 

@knighton I'll approve it now but before merging could you add a quick test to `test_streaming.py` for when `remote=None`?

**Comment by knighton** [comment]
Will do

**Comment by knighton** [comment]
@ravi-mosaicml https://mosaicml-composer--1220.com.readthedocs.build/en/1220/api_reference/composer.datasets.streaming.dataset.html#module-composer.datasets.streaming.dataset fixed

**Pull request merged**
