### PR TITLE
Add a `EVAL_STANDALONE_START` and `EVAL_STANDALONE_END` events and change RUD to not `wait_for_workers` every eval

### PR DESCRIPTION
**Pull request by dakinggg**
# What does this PR do?
Previously, `RemoteUploaderDownloader.wait_for_workers` was called on the `eval_end` event. This meant that `wait_for_workers` would happen after _every_ individual evaluator loop. This results in unnecessary hangs waiting for checkpoint upload in the middle of a run. This PR adds new events to signify that the standalone `trainer.eval` is being called, as opposed to eval from within the training loop, and changes the `RemoteUploaderDownloader` to use that event instead of the `eval_end` event. It also spawns a new issue [CO-2268](https://mosaicml.atlassian.net/browse/CO-2268).

# What issue(s) does this change relate to?
Closes [CO-2267](https://mosaicml.atlassian.net/browse/CO-2267)

# Manual test
Manual test is by running
```
composer train.py yamls/finetune/mpt-7b_dolly_sft.yaml max_duration=5ba global_train_batch_size=4 device_train_microbatch_size=1 save_folder=oci://mosaicml-internal-checkpoints/daniel/checkpoints/{run_name} eval_subset_num_batches=2 eval_first=False optimizer.name=decoupled_lionw model.pretrained=False dist_timeout=20 loggers.wandb={} model.config_overrides.d_model=256 model.config_overrides.n_layers=12 run_name=test-run eval_interval=2ba autoresume=False save_overwrite=True save_interval=1ba
```
Before this PR it would hang after each eval, after this pr it just waits at the end of the run for the uploads to complete.

# Before submitting
- [x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [x] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [x] Did you update any related docs and document your change?
- [x] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [x] Did you run the tests locally to make sure they pass?
- [x] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

[CO-2268]: https://mosaicml.atlassian.net/browse/CO-2268?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[CO-2267]: https://mosaicml.atlassian.net/browse/CO-2267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by mvpatel2000 — APPROVED** [review]
Can you please update docs to include this event? Is there anywhere it should be included?

**Comment by dakinggg** [comment]
@mvpatel2000 In looking at that, I've discovered we don't document the "predict" events anywhere, which would be analogous to this. Any suggestions where to put these new event docs?

**Comment by mvpatel2000** [comment]
> @mvpatel2000 In looking at that, I've discovered we don't document the "predict" events anywhere, which would be analogous to this. Any suggestions where to put these new event docs?

hm... in this case I think it's fine to leave off for now? I would rather keep the events section focused on training and simple vs. detailing the more "advanced" events. How about we open a jira and include this in the docs refactor (I'll follow up on this actually happening)

**Comment by dakinggg** [comment]
[CO-2270](https://mosaicml.atlassian.net/browse/CO-2270)

**Review by eracah — APPROVED** [review]
LGTM

**Pull request merged**
