### PR TITLE
Don't use TP when `tensor_parallel_degree` is 1

### PR DESCRIPTION
**Pull request by snarayan21**
# What does this PR do?

Marked as draft since it depends on #3434 

Disables tensor parallelism when the `tensor_parallelism_degree` is 1. This should be a no-op and any TP setup steps can be completely skipped. Added a warning so users will know, and modified tp test to catch this warning too. Otherwise, we run into ugly errors (during training as well as generation) such as:

```
[rank0]: Traceback (most recent call last):
[rank0]:   File "/llm-foundry/scripts/train/train.py", line 600, in <module>
[rank0]:     main(cfg)
[rank0]:   File "/llm-foundry/scripts/train/train.py", line 582, in main
[rank0]:     trainer.fit()
[rank0]:   File "/composer/composer/trainer/trainer.py", line 2340, in fit
[rank0]:     self._train_loop()
[rank0]:   File "/composer/composer/trainer/trainer.py", line 2550, in _train_loop
[rank0]:     total_loss_dict = self._train_batch(use_grad_scaling)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/composer/composer/trainer/trainer.py", line 2759, in _train_batch
[rank0]:     optimizer.step(
[rank0]:   File "/usr/lib/python3/dist-packages/torch/optim/lr_scheduler.py", line 75, in wrapper
[rank0]:     return wrapped(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/optim/optimizer.py", line 391, in wrapper
[rank0]:     out = func(*args, **kwargs)
[rank0]:           ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
[rank0]:     return func(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llm-foundry-private/llmfoundry/optim/lion.py", line 91, in step
[rank0]:     loss = closure()
[rank0]:            ^^^^^^^^^
[rank0]:   File "/composer/composer/trainer/trainer.py", line 2761, in <lambda>
[rank0]:     **kwargs: self._train_microbatches(microbatches, loss_dict, **kwargs).item(),
[rank0]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/composer/composer/trainer/trainer.py", line 2883, in _train_microbatches
[rank0]:     microbatch_loss_dict = self._train_microbatch(use_grad_scaling, current_batch_size, is_final_microbatch)
[rank0]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/composer/composer/trainer/trainer.py", line 2959, in _train_microbatch
[rank0]:     self.state.outputs = self.state.model(self.state.batch)
[rank0]:                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llm-foundry-private/llmfoundry/models/mpt/modeling_mpt.py", line 1209, in forward
[rank0]:     return self.model(
[rank0]:            ^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 857, in forward
[rank0]:     output = self._fsdp_wrapped_module(*args, **kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llm-foundry-private/llmfoundry/models/mpt/modeling_mpt.py", line 939, in forward
[rank0]:     outputs = self.transformer(
[rank0]:               ^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llm-foundry-private/llmfoundry/models/mpt/modeling_mpt.py", line 768, in forward
[rank0]:     x, attn_weights, present = block(
[rank0]:                                ^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 857, in forward
[rank0]:     output = self._fsdp_wrapped_module(*args, **kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llm-foundry-private/llmfoundry/models/layers/blocks.py", line 183, in forward
[rank0]:     b, attn_weights, past_key_value = self.attn(
[rank0]:                                       ^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1541, in _call_impl
[rank0]:     return forward_call(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llm-foundry-private/llmfoundry/models/layers/attention.py", line 515, in forward
[rank0]:     query, key, value = self.get_qkv(x)
[rank0]:                         ^^^^^^^^^^^^^^^
[rank0]:   File "/llm-foundry-private/llmfoundry/models/layers/attention.py", line 798, in get_qkv
[rank0]:     query, key, value = super().get_qkv(x)
[rank0]:                         ^^^^^^^^^^^^^^^^^^
[rank0]:   File "/llm-foundry-private/llmfoundry/models/layers/attention.py", line 563, in get_qkv
[rank0]:     qkv = self.Wqkv(x)
[rank0]:           ^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1532, in _wrapped_call_impl
[rank0]:     return self._call_impl(*args, **kwargs)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/module.py", line 1582, in _call_impl
[rank0]:     result = forward_call(*args, **kwargs)
[rank0]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/nn/modules/linear.py", line 116, in forward
[rank0]:     return F.linear(input, self.weight, self.bias)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/api.py", line 279, in __torch_dispatch__
[rank0]:     return DTensor._op_dispatcher.dispatch(
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/dispatch.py", line 113, in dispatch
[rank0]:     self.sharding_propagator.propagate(op_info)
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/sharding_prop.py", line 165, in propagate
[rank0]:     output_sharding = self.propagate_op_sharding(op_info.schema)
[rank0]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/sharding_prop.py", line 213, in propagate_op_sharding_non_cached
[rank0]:     op_strategy = self.op_strategy_funcs[op_schema.op](mesh, strategy_schema)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/ops/matrix_ops.py", line 133, in addmm_strategy
[rank0]:     return _addmm_like_strategy("mk,kn->mn", mesh, op_schema)
[rank0]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/ops/matrix_ops.py", line 87, in _addmm_like_strategy
[rank0]:     mm_strategy = gen_einsum_strategies(mm_equation, mesh)
[rank0]:                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[rank0]:   File "/usr/lib/python3/dist-packages/torch/distributed/_tensor/ops/basic_strategy.py", line 181, in gen_einsum_strategies
[rank0]:     strat = PlacementStrategy(output_specs=spec_list[0], input_specs=spec_list[1:])
[rank0]:                                            ~~~~~~~~~^^^
[rank0]: IndexError: list index out of range
```

# What issue(s) does this change relate to?

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

### CODE REVIEW

**Review by mvpatel2000 — COMMENTED** [review]
LGTM, plz rerequest after first PR is merged

**Comment by eitanturok** [comment]
Wanted to follow up on this PR. Seems like we should merge this. Any way I can with this?

**Review by snarayan21 — COMMENTED** [review]
seems fine to me but the tests are failing. Also has merge conflicts

**Comment by eitanturok** [comment]
Closing because completed in #3636.

**Pull request closed without merging**
