### PR TITLE
fix log epoch

### PR DESCRIPTION
**Pull request by mvpatel2000**
# What does this PR do?

Change to trainer/epoch when logging

[CO-1812
](https://mosaicml.atlassian.net/browse/CO-1812)

### CODE REVIEW

**Review by dakinggg — COMMENTED** [review]
LGTM, but could you paste in some wandb screenshot to prove it works?

**Comment by mvpatel2000** [comment]
image
Now moved under `/trainer/`

**Comment by dakinggg** [comment]
Should there be a data point in that image?

**Comment by mvpatel2000** [comment]
> Should there be a data point in that image?
Hm... I don't know what happened there... I checked again and it's there?? maybe it was buffering...

image

**Comment by mvpatel2000** [comment]
image
Here's a new run new project. I'm going to claim wandb bug

**Review by dakinggg — APPROVED** [review]

**Pull request merged**
