### PR TITLE
Bump version to 0.13.1

### PR DESCRIPTION
**Pull request by bandish-shah**
# What does this PR do?

Bumps Composer version to v0.13.1.

# What issue(s) does this change relate to?

n/a

# Before submitting
- [x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [x] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

### CODE REVIEW

**Review by mvpatel2000 — APPROVED** [review]
please wait until hanlin's pr lands before merging

**Comment by dakinggg** [comment]
I'd like to wait for 1) hanlin's pr to merge, 2) CI to pass on this pr (https://github.com/mosaicml/composer/pull/2032) after merging in hanlin's pr

**Comment by mvpatel2000** [comment]
Why is diff weird now?

**Comment by bandish-shah** [comment]
I manually merged the other branches ahead of this to get a head start on the CI.

**Pull request merged**
