### PR TITLE
Update NCCL_ASYNC_ERROR_HANDLING env variable

### PR DESCRIPTION
**Pull request by priba**
# What does this PR do?

The environment variable `NCCL_ASYNC_ERROR_HANDLING` is deprecated and it is suggested to use `TORCH_NCCL_ASYNC_ERROR_HANDLING` instead.

# What issue(s) does this change relate to?

Applies #3266 

# Before submitting
- [x] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [x] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [x] Did you run the tests locally to make sure they pass?
- [x] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

### CODE REVIEW

**Comment by mvpatel2000** [comment]
It looks like this is introduced in [torch 2.2](https://github.com/pytorch/pytorch/blob/release/2.2/torch/csrc/distributed/c10d/logger.cpp#L16-L21) and doesn't exist in [torch 2.1](https://github.com/pytorch/pytorch/blob/release/2.1/torch/csrc/distributed/c10d/logger.cpp#L10-L21). Since we try to support the last 3 minor versions of torch, we unfortunately can't switch until torch 2.4 comes out. I can merge this PR then! Thanks for opening it.

**Comment by priba** [comment]
Shall we make it conditional? Something like:

```python
from packaging import version

if version.parse(torch.__version__) <= version.parse('2.2.0'):
     to_patch = {"NCCL_ASYNC_ERROR_HANDLING": '1'}
else:
     to_patch = {"TORCH_NCCL_ASYNC_ERROR_HANDLING"='1'}

...

with _patch_env(**to_patch ):
```

Not sure if it is worth though.

**Comment by mvpatel2000** [comment]
> Shall we make it conditional? Something like:

@priba that would also work! happy to accept that as a PR :)

**Review by mvpatel2000 — APPROVED** [review]
LGTM, thanks for the PR!

**Pull request merged**
