### PR TITLE
Correctly process `parallelism_config['tp']` when it's a dict

### PR DESCRIPTION
**Pull request by snarayan21**
# What does this PR do?
This fixes a bug where if the TP configuration (specified through `parallelism_config['tp']`) was passed in as a dict, it would not be correctly processed into the final `parallelism_config`. This also means that whenever we were specifying the TP config as a dict before, it was not actually being set.

Modified unit tests to make sure the TP config is actually being set.

# What issue(s) does this change relate to?

# Before submitting
- [ ] Have you read the [contributor guidelines](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md)?
- [ ] Is this change a documentation change or typo fix? If so, skip the rest of this checklist.
- [ ] Was this change discussed/approved in a GitHub issue first? It is much more likely to be merged if so.
- [ ] Did you update any related docs and document your change?
- [ ] Did you update any related tests and add any new tests related to your change? (see [testing](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#running-tests))
- [ ] Did you run the tests locally to make sure they pass?
- [ ] Did you run `pre-commit` on your change? (see the `pre-commit` section of [prerequisites](https://github.com/mosaicml/composer/blob/dev/CONTRIBUTING.md#prerequisites))

### CODE REVIEW

**Review by mvpatel2000 — DISMISSED** [review]
oof good catch

**Comment by snarayan21** [comment]
@mvpatel2000 I keep getting errors on 4 gpu tests because it's detecting the `FutureWarning` and counting that as an error. I've tried filtering out these warnings but that doesn't seem to be working, including adding the warning to the pyproject.toml config for pytest. What's the right way to filter these?

**Comment by mvpatel2000** [comment]
> @mvpatel2000 I keep getting errors on 4 gpu tests because it's detecting the `FutureWarning` and counting that as an error. I've tried filtering out these warnings but that doesn't seem to be working, including adding the warning to the pyproject.toml config for pytest. What's the right way to filter these?

pytest.mark.filterwarning?

**Comment by snarayan21** [comment]
@mvpatel2000 I already added this `@pytest.mark.filterwarnings('ignore:.*(TP) is experimental.*:FutureWarning')` on all relevant tests...

**Comment by mvpatel2000** [comment]
> @mvpatel2000 I already added this `@pytest.mark.filterwarnings('ignore:.*(TP) is experimental.*:FutureWarning')` on all relevant tests...

I think its a regex issue, should be `\(`?

**Comment by snarayan21** [comment]
ah that makes sense @mvpatel2000 lemme try

**Review by mvpatel2000 — APPROVED** [review]
LGTM

**Pull request merged**
